services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres

  worker:
    build: .
    command: npm run worker
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: leaderboard